---
- name: Ensure haproxy is installed
  apt: name=haproxy state=present

- name: Ensure haproxy is enabled
  lineinfile:
    dest: /etc/default/haproxy
    regexp: "^ENABLED.+$"
    line: "ENABLED=1"
    state: present

- name: Copy haproxy config file
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: 0644
    validate: haproxy -f %s -c -q
  notify: Restart haproxy

- name: Ensure haproxy start at boot time
  service: name=haproxy state=started enabled=yes
