---

- name: Install unzip
  apt: name=unzip state=present

- name: Check if wp is already downloaded
  stat: path="{{ wp_download_path }}"
  register: wp_zipped

- name: Download wordpress
  get_url: url="{{ wp_url }}" dest="{{ wp_download_path }}"
  when: wp_zipped.stat.exists == False

- name: Unzip wordpress
  unarchive: src="{{ wp_download_path  }}" dest="{{ wp_webserver_path }}" copy=no

- name: Copy wp-config
  template: src=wp-config.php.j2 dest="{{ wp_webserver_path }}/wp-config.php"

    
   
